FROM jupyter/tensorflow-notebook

# any other standard conda packages packages here
RUN pip --no-cache-dir install --quiet \
    biopython \
    jupyterlab \
    pandas \
    numpy \
    sklearn \
    matplotlib \
    seaborn \
    clustalo 

