version: '2.3' # Rollback version to 2.3 to enable nvidia container runtime 
services:

  jupyter:
    build: ./gpu # select computing platform
    runtime: nvidia
    restart: always
    container_name: tflow-jupyter

    environment:

      # Configure HTTPS:
      VIRTUAL_HOST: subdomain.domain.com
      LETSENCRYPT_HOST: subdomain.domain.com
      LETSENCRYPT_EMAIL: your@email.com

      # Use lab in place of notebook 
      JUPYTER_ENABLE_LAB: 'yes'

    volumes:
      - "/your/local/directory:/tf/notebooks" # For GPU

# Connect to reverse proxy:
networks:
  default:
    external:
      name: proxy_proxy-tier 
